sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t kylef26/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kylef26/docker-react npm run test